branch-defaults:
  default:
    environment: MgmresortsReactive-env
    group_suffix: null
deploy:
  artifact: target/testpublicrepo-1.0.jar
global:
  application_name: mgmresorts-reactive
  default_ec2_keyname: ujenk
  default_platform: Java 8
  default_region: us-east-1
  include_git_submodules: true
  sc: git
  workspace_type: Application
