version: 2
jobs:
  build:
    
    working_directory: ~/project

    docker:
      - image: circleci/openjdk:8-jdk-browsers
       
    steps:

      - checkout

      - restore_cache:
          key: circleci-mgmresorts-reactive-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-mgmresorts-reactive-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/testpublicrepo-1.0.jar

      - run:
          name: Save jar to an workspace folder
          command: |
            mkdir spring-jar
            cp -R target/testpublicrepo-1.0.jar spring-jar

      - persist_to_workspace:
          root: .
          paths:
            - spring-jar

  deploy:  
    docker:
      - image: circleci/python:3.6.1
    environment:
      AWS_DEFAULT_OUTPUT: json
    steps:
      - run:
          name: Install awscli
          command: pip install awsebcli --upgrade --user
      - run:
          name: check eb version
          command: eb --version

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build